Repository CMSgov/blueprint_api, pull requests merged in 2022-09, with the labels that each got.

#85 Add linting workflow
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
  access_management/permission_constants.py
  access_management/utils.py
  blueprintapi/authentication.py
  blueprintapi/environment.py
  blueprintapi/settings.py
  blueprintapi/tests.py
  blueprintapi/urls.py
  blueprintapi/views.py
  catalogs/catalogio.py
  catalogs/management/commands/load_catalog.py
  catalogs/models.py
  catalogs/signals.py
  catalogs/tests.py
  catalogs/tests_catalogio.py
  components/componentio.py
  components/filters.py
  components/forms.py
  components/serializers.py
  components/signals.py
  components/tests.py
  components/views.py
  poetry.lock
  projects/models.py
  projects/signals.py
  projects/views.py
  pyproject.toml
  users/signals.py
  users/tests.py
Labels: enhancement, github_actions

#99 Add test componenets
  blueprintapi/oscal/component.py
  blueprintapi/tests.py
  components/data/aws.json
  components/data/blueprint.json
  components/data/django.json
  components/data/idm.json
  components/data/ociso.json
  components/data/splunk.json
  components/data/tenable_nessus.json
  components/data/trendmicro.json
  components/management/__init__.py
  components/management/commands/__init__.py
  components/management/commands/load_components.py
  components/tests.py
Labels: enhancement

#104 Add private component id to project info
  projects/serializers.py
  projects/tests.py
Labels: enhancement

#110 Update and sync python version to 3.10
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
  Dockerfile
  blueprintapi/environment.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#109 Check token expiration before responding
  blueprintapi/tests.py
  blueprintapi/views.py
Labels: bug

#112 Use updated poetry version
  Dockerfile
Labels: bug

#111 Add session auth
  blueprintapi/settings.py
  blueprintapi/tests.py
  blueprintapi/urls.py
  blueprintapi/views.py
Labels: enhancement

#113 1257 decouple components catalogs
  blueprintapi/oscal/component.py
  catalogs/catalogio.py
  catalogs/management/commands/load_catalog.py
  catalogs/migrations/0006_alter_catalog_version.py
  catalogs/migrations/0007_alter_catalog_unique_together.py
  catalogs/models.py
  components/admin.py
  components/apps.py
  components/componentio.py
  components/filters.py
  components/forms.py
  components/management/commands/load_components.py
  components/migrations/0005_remove_component_catalog_and_more.py
  components/models.py
  components/serializers.py
  components/signals.py
  components/tests.py
  projects/signals.py
  projects/tests.py
  projects/views.py
Labels: enhancement

#115 Fix controls ordering
  catalogs/catalogio.py
  projects/tests.py
  projects/views.py
Labels: bug

#117 Fix swagger request schemes
  blueprintapi/urls.py
Labels: bug

#118 Bug/fix add narrative
  blueprintapi/oscal/component.py
  components/serializers.py
  components/tests.py
  projects/serializers.py
Labels: bug

#121 Update README.md
  README.md
Labels: documentation

#120 Feature/add 5.0 catalogs
  catalogs/data/5.0/cms_ars_50_high.json
  catalogs/data/5.0/cms_ars_50_low.json
  catalogs/data/5.0/cms_ars_50_moderate.json
  catalogs/io/__init__.py
  catalogs/io/v5_0.py
  catalogs/migrations/0008_alter_controls_control_label_alter_controls_sort_id.py
  catalogs/models.py
  catalogs/signals.py
  catalogs/tests.py
  catalogs/views.py
  components/data/django.json
  components/tests.py
  projects/serializers.py
  projects/tests.py
  pyproject.toml
Labels: enhancement

#116 Feature/1236 non applicable
  projects/migrations/0009_projectcontrol_remarks_alter_projectcontrol_status.py
  projects/models.py
  projects/serializers.py
Labels: enhancement

#125 Fix ProjectControl status and "completed" count
  projects/migrations/0009_projectcontrol_remarks_alter_projectcontrol_status.py
  projects/models.py
  projects/tests.py
  projects/views.py
Labels: bug

#124 1018 disable narratives
  projects/migrations/0009_projectcontrol_disabled_narratives_and_more.py
  projects/models.py
  projects/serializers.py
  projects/tests.py
Labels: enhancement
