Repository CMSgov/blueprint_api, pull requests merged in 2022-08, with the labels that each got.

#60 Feature/1178 authenticate apis
  blueprintapi/settings.py
  blueprintapi/tests.py
  blueprintapi/urls.py
  blueprintapi/views.py
  catalogs/tests.py
  components/tests.py
  poetry.lock
  projects/tests.py
  pyproject.toml
  testing_utils.py
  users/models.py
  users/tests.py
Labels: enhancement

#67 [1160] Adding SwaggerUI
  README.md
  blueprintapi/settings.py
  blueprintapi/urls.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#69 Add unittests Actions workflow
  .github/dependabot.yml
  .github/workflows/test.yaml
Labels: enhancement

#74 Fix syntax error in test workflow
  .github/workflows/test.yaml
Labels: bug

#76 Add missing environment variables
  .github/workflows/test.yaml
Labels: bug, github_actions

#66 Feature/1178 authenticate apis
  access_management/utils.py
  blueprintapi/authentication.py
  blueprintapi/filters.py
  blueprintapi/permissions.py
  blueprintapi/settings.py
  blueprintapi/tests.py
  blueprintapi/urls.py
  blueprintapi/views.py
  catalogs/tests.py
  catalogs/urls.py
  catalogs/views.py
  components/filters.py
  components/tests.py
  components/views.py
  poetry.lock
  projects/tests.py
  projects/views.py
  pyproject.toml
  testing_utils.py
  users/models.py
  users/tests.py
Labels: enhancement

#79 Bug/open create user perms
  access_management/permission_constants.py
  blueprintapi/views.py
  projects/serializers.py
  projects/tests.py
  users/models.py
  users/permissions.py
  users/serializers.py
  users/tests.py
  users/views.py
Labels: bug

#78 added a sort for get_control_ids
  catalogs/catalogio.py
  catalogs/tests_catalogio.py
  components/tests.py
  projects/tests.py
  projects/views.py
Labels: enhancement

#82 Bug/add component permissions
  components/filters.py
  components/permissions.py
  components/views.py
  projects/models.py
  users/models.py
Labels: bug

#88 Bug/Fix duplicate types in component types endpoint
  components/filters.py
  components/tests.py
  components/views.py
Labels: bug

#84 Feature/1166 project control
  blueprintapi/settings.py
  blueprintapi/testdata/NIST_SP-800-53_rev5_test.json
  catalogs/catalogio.py
  catalogs/migrations/0005_catalog_impact_level_catalog_version_controls.py
  catalogs/models.py
  catalogs/serializers.py
  catalogs/tests_catalogio.py
  components/models.py
  components/tests.py
  projects/filters.py
  projects/migrations/0007_projectcontrol_project_catalog_version_and_more.py
  projects/models.py
  projects/serializers.py
  projects/tests.py
  projects/urls.py
  projects/views.py
  users/tests.py
Labels: enhancement

#93 Feature/add percent complete
  projects/serializers.py
  projects/tests.py
  projects/views.py
Labels: enhancement

#94 Refactor signals
  catalogs/apps.py
  catalogs/models.py
  catalogs/signals.py
  components/apps.py
  components/models.py
  components/signals.py
  projects/apps.py
  projects/models.py
  projects/signals.py
  projects/tests.py
  users/apps.py
  users/models.py
  users/signals.py
Labels: enhancement

#95 589: Updating logging formats.
  blueprintapi/settings.py
  users/apps.py
  users/signals.py
Labels: enhancement

#89 Add endpoint for updating a component's control narrratives
  blueprintapi/oscal/component.py
  components/componentio.py
  components/permissions.py
  components/serializers.py
  components/tests.py
  components/urls.py
  components/views.py
Labels: enhancement

#96 Feature/catalog import am
  .gitignore
  blueprintapi/Environment.py
  blueprintapi/settings.py
  catalogs/data/3.1/CMS_ARS_3_1_HIGH-baseline_catalog.json
  catalogs/data/3.1/CMS_ARS_3_1_LOW-baseline_catalog.json
  catalogs/data/3.1/CMS_ARS_3_1_MODERATE-baseline_catalog.json
  catalogs/data/README.md
  catalogs/management/commands/load_catalog.py
  catalogs/tests.py
Labels: enhancement
